"""skema awal (tiket 09)

Revision ID: 0001
Revises:
Create Date: 2026-09-22 20:19:29.544700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aturan_predikat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tingkat_seleksi_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('batas_bawah', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('batas_bawah >= 0 AND batas_bawah <= 100', name='ck_aturan_predikat_rentang'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tingkat_seleksi_id', 'label')
    )
    op.create_table('hasil_tes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('sekolah_id', sa.Integer(), nullable=True),
    sa.Column('tingkat_seleksi_id', sa.Integer(), nullable=False),
    sa.Column('jenis_tes', sa.Enum('pre_test', 'simulasi', name='jenistes', native_enum=False), nullable=False),
    sa.Column('simulasi_id', sa.Integer(), nullable=True),
    sa.Column('total_soal', sa.Integer(), nullable=False),
    sa.Column('jumlah_benar', sa.Integer(), nullable=False),
    sa.Column('jumlah_salah', sa.Integer(), nullable=False),
    sa.Column('skor', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('predikat_label', sa.String(), nullable=False),
    sa.Column('diselesaikan_pada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(jenis_tes = 'simulasi' AND simulasi_id IS NOT NULL) OR (jenis_tes = 'pre_test' AND simulasi_id IS NULL)", name='ck_hasil_tes_simulasi_id_konsisten'),
    sa.CheckConstraint('skor >= 0 AND skor <= 100', name='ck_hasil_tes_skor_rentang'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kompetensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_materi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('materi_id', sa.Integer(), nullable=False),
    sa.Column('subkompetensi_id', sa.Integer(), nullable=False),
    sa.Column('tingkat_seleksi_id', sa.Integer(), nullable=False),
    sa.Column('total_halaman', sa.Integer(), nullable=False),
    sa.Column('halaman_tertinggi_dicapai', sa.Integer(), nullable=False),
    sa.Column('pertama_dibuka_pada', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('diperbarui_pada', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('halaman_tertinggi_dicapai >= 1 AND halaman_tertinggi_dicapai <= total_halaman', name='ck_progress_materi_halaman_dalam_rentang'),
    sa.CheckConstraint('total_halaman > 0', name='ck_progress_materi_total_halaman_positif'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siswa_id', 'materi_id')
    )
    op.create_table('tingkat_seleksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urutan')
    )
    op.create_table('aturan_pemetaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tingkat_seleksi_id', sa.Integer(), nullable=False),
    sa.Column('ambang_cukup_persen', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('ambang_representasi_persen', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.CheckConstraint('ambang_cukup_persen >= 0 AND ambang_cukup_persen <= 100', name='ck_aturan_pemetaan_ambang_cukup_rentang'),
    sa.CheckConstraint('ambang_representasi_persen >= 0 AND ambang_representasi_persen <= 100', name='ck_aturan_pemetaan_ambang_representasi_rentang'),
    sa.ForeignKeyConstraint(['tingkat_seleksi_id'], ['tingkat_seleksi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tingkat_seleksi_id')
    )
    op.create_table('hasil_tes_subkompetensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasil_tes_id', sa.Integer(), nullable=False),
    sa.Column('subkompetensi_id', sa.Integer(), nullable=False),
    sa.Column('jumlah_soal', sa.Integer(), nullable=False),
    sa.Column('jumlah_benar', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hasil_tes_id'], ['hasil_tes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hasil_tes_id', 'subkompetensi_id')
    )
    op.create_table('subkompetensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kompetensi_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kompetensi_id'], ['kompetensi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subkompetensi_id', sa.Integer(), nullable=False),
    sa.Column('tingkat_seleksi_id', sa.Integer(), nullable=False),
    sa.Column('nomor', sa.Integer(), nullable=False),
    sa.Column('pertanyaan', sa.String(), nullable=False),
    sa.Column('pilihan_jawaban', sa.JSON(), nullable=False),
    sa.Column('kunci_jawaban', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subkompetensi_id'], ['subkompetensi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tingkat_seleksi_id'], ['tingkat_seleksi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tingkat_seleksi_id', 'nomor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soal')
    op.drop_table('subkompetensi')
    op.drop_table('hasil_tes_subkompetensi')
    op.drop_table('aturan_pemetaan')
    op.drop_table('tingkat_seleksi')
    op.drop_table('progress_materi')
    op.drop_table('kompetensi')
    op.drop_table('hasil_tes')
    op.drop_table('aturan_predikat')
    # ### end Alembic commands ###
