"""kontrak api pemetaan rekomendasi tiket 11

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-22 21:59:42.786468

Diedit setelah dibuat (fase 2 issue 01): revisi ini sebelumnya hanya pernah
jalan di SQLite dan GAGAL di Postgres (urutan DROP FK/ALTER TYPE, default
boolean). Karena tidak ada database Postgres yang pernah berhasil melewati
revisi ini, perbaikannya aman diterapkan di tempat.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jawaban_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasil_tes_id', sa.Integer(), nullable=False),
    sa.Column('soal_id', sa.String(), nullable=False),
    sa.Column('subkompetensi_id', sa.String(), nullable=False),
    sa.Column('jawaban_dipilih', sa.String(), nullable=False),
    sa.Column('is_benar', sa.Boolean(), nullable=False),
    sa.Column('durasi_detik', sa.Integer(), nullable=False),
    sa.Column('is_lambat', sa.Boolean(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hasil_tes_id'], ['hasil_tes.id'], name=op.f('fk_jawaban_siswa_hasil_tes_id_hasil_tes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jawaban_siswa'))
    )
    with op.batch_alter_table('aturan_pemetaan', schema=None) as batch_op:
        # FK dilepas SEBELUM tipe kolom diubah — Postgres menolak ALTER TYPE
        # selama FK int->int masih melekat (SQLite batch mode tidak peduli).
        batch_op.drop_constraint(batch_op.f('fk_aturan_pemetaan_tingkat_seleksi_id_tingkat_seleksi'), type_='foreignkey')
        batch_op.alter_column('tingkat_seleksi_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('aturan_predikat', schema=None) as batch_op:
        batch_op.alter_column('tingkat_seleksi_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('hasil_tes', schema=None) as batch_op:
        batch_op.alter_column('siswa_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('sekolah_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('tingkat_seleksi_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('simulasi_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('hasil_tes_subkompetensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_pemetaan', sa.Enum('cukup', 'belum_cukup', 'belum_teruji', name='statuspemetaan', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('butuh_optimasi', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.alter_column('subkompetensi_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('soal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batas_waktu_detik', sa.Integer(), server_default='60', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soal', schema=None) as batch_op:
        batch_op.drop_column('batas_waktu_detik')

    with op.batch_alter_table('hasil_tes_subkompetensi', schema=None) as batch_op:
        batch_op.alter_column('subkompetensi_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('butuh_optimasi')
        batch_op.drop_column('status_pemetaan')

    with op.batch_alter_table('hasil_tes', schema=None) as batch_op:
        batch_op.alter_column('simulasi_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('tingkat_seleksi_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('sekolah_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('siswa_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('aturan_predikat', schema=None) as batch_op:
        batch_op.alter_column('tingkat_seleksi_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('aturan_pemetaan', schema=None) as batch_op:
        batch_op.alter_column('tingkat_seleksi_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='tingkat_seleksi_id::integer')
        batch_op.create_foreign_key(batch_op.f('fk_aturan_pemetaan_tingkat_seleksi_id_tingkat_seleksi'), 'tingkat_seleksi', ['tingkat_seleksi_id'], ['id'], ondelete='CASCADE')

    op.drop_table('jawaban_siswa')
    # ### end Alembic commands ###
