"""kenaikan tingkat dan dashboard tiket 03 04

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-22 23:06:32.000824

Diedit setelah dibuat (fase 2 issue 01): revisi ini sebelumnya hanya pernah
jalan di SQLite dan GAGAL di Postgres (urutan DROP FK/ALTER TYPE, default
boolean). Karena tidak ada database Postgres yang pernah berhasil melewati
revisi ini, perbaikannya aman diterapkan di tempat.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akses_tingkat_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('tingkat_seleksi_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dibuka_karena', sa.String(), nullable=True),
    sa.Column('hasil_tes_id', sa.Integer(), nullable=True),
    sa.Column('dibuka_pada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('diperbarui_pada', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hasil_tes_id'], ['hasil_tes.id'], name=op.f('fk_akses_tingkat_siswa_hasil_tes_id_hasil_tes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tingkat_seleksi_id'], ['tingkat_seleksi.id'], name=op.f('fk_akses_tingkat_siswa_tingkat_seleksi_id_tingkat_seleksi'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_akses_tingkat_siswa')),
    sa.UniqueConstraint('siswa_id', 'tingkat_seleksi_id', name=op.f('uq_akses_tingkat_siswa_siswa_id'))
    )
    op.create_table('aturan_kenaikan_tingkat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tingkat_asal_id', sa.Integer(), nullable=False),
    sa.Column('tingkat_tujuan_id', sa.Integer(), nullable=False),
    sa.Column('skor_simulasi_min', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('persentase_kompetensi_cukup_min', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('aktif', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.CheckConstraint('persentase_kompetensi_cukup_min >= 0 AND persentase_kompetensi_cukup_min <= 100', name=op.f('ck_aturan_kenaikan_tingkat_ck_aturan_kenaikan_persentase_rentang')),
    sa.CheckConstraint('skor_simulasi_min >= 0 AND skor_simulasi_min <= 100', name=op.f('ck_aturan_kenaikan_tingkat_ck_aturan_kenaikan_skor_rentang')),
    sa.ForeignKeyConstraint(['tingkat_asal_id'], ['tingkat_seleksi.id'], name=op.f('fk_aturan_kenaikan_tingkat_tingkat_asal_id_tingkat_seleksi'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tingkat_tujuan_id'], ['tingkat_seleksi.id'], name=op.f('fk_aturan_kenaikan_tingkat_tingkat_tujuan_id_tingkat_seleksi'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aturan_kenaikan_tingkat')),
    sa.UniqueConstraint('tingkat_asal_id', 'tingkat_tujuan_id', name=op.f('uq_aturan_kenaikan_tingkat_tingkat_asal_id'))
    )
    op.create_table('riwayat_evaluasi_kenaikan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('hasil_tes_id', sa.Integer(), nullable=False),
    sa.Column('aturan_kenaikan_id', sa.Integer(), nullable=False),
    sa.Column('skor_aktual', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('skor_target', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('syarat_skor_lulus', sa.Boolean(), nullable=False),
    sa.Column('persentase_cukup_aktual', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('persentase_cukup_target', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('syarat_kompetensi_lulus', sa.Boolean(), nullable=False),
    sa.Column('hasil_evaluasi', sa.String(), nullable=False),
    sa.Column('dievaluasi_pada', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aturan_kenaikan_id'], ['aturan_kenaikan_tingkat.id'], name=op.f('fk_riwayat_evaluasi_kenaikan_aturan_kenaikan_id_aturan_kenaikan_tingkat'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hasil_tes_id'], ['hasil_tes.id'], name=op.f('fk_riwayat_evaluasi_kenaikan_hasil_tes_id_hasil_tes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_riwayat_evaluasi_kenaikan'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riwayat_evaluasi_kenaikan')
    op.drop_table('aturan_kenaikan_tingkat')
    op.drop_table('akses_tingkat_siswa')
    # ### end Alembic commands ###
