"""gerbang pretest paket tes (fase 2 issue 02)

Tingkat Seleksi hanya Kabupaten & Provinsi (Nasional dihapus). Status akses
diperluas (terkunci/pretest_terbuka/terbuka), aturan kenaikan memakai jalur
cepat pre-test & rata-rata Level Soal Siswa (menggantikan % kompetensi cukup),
serta tabel Paket Tes, Level Soal Siswa, Hasil Tes per Materi, Aturan Adaptif.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-28 23:26:17.703323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aturan_adaptif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tingkat_seleksi_id', sa.Integer(), nullable=False),
    sa.Column('jumlah_soal_pretest', sa.Integer(), nullable=False),
    sa.Column('ambang_lemah', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.CheckConstraint('ambang_lemah >= 0 AND ambang_lemah <= 100', name=op.f('ck_aturan_adaptif_ck_aturan_adaptif_ambang_lemah_rentang')),
    sa.CheckConstraint('jumlah_soal_pretest > 0', name=op.f('ck_aturan_adaptif_ck_aturan_adaptif_jumlah_pretest_positif')),
    sa.ForeignKeyConstraint(['tingkat_seleksi_id'], ['tingkat_seleksi.id'], name=op.f('fk_aturan_adaptif_tingkat_seleksi_id_tingkat_seleksi'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aturan_adaptif')),
    sa.UniqueConstraint('tingkat_seleksi_id', name=op.f('uq_aturan_adaptif_tingkat_seleksi_id'))
    )
    op.create_table('paket_tes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('tingkat_seleksi_id', sa.Integer(), nullable=False),
    sa.Column('jenis_tes', sa.Enum('pre_test', 'simulasi', name='jenistes', native_enum=False), nullable=False),
    sa.Column('jumlah_soal_diminta', sa.Integer(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disubmit_pada', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tingkat_seleksi_id'], ['tingkat_seleksi.id'], name=op.f('fk_paket_tes_tingkat_seleksi_id_tingkat_seleksi'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paket_tes'))
    )
    with op.batch_alter_table('paket_tes', schema=None) as batch_op:
        batch_op.create_index('uq_paket_tes_pretest_per_siswa_tingkat', ['siswa_id', 'tingkat_seleksi_id'], unique=True, postgresql_where=sa.text("jenis_tes = 'pre_test'"))

    op.create_table('level_soal_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('materi_id', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('mudah', 'menengah', 'sulit', name='levelsoal', native_enum=False), nullable=False),
    sa.Column('akurasi_terakhir', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=True),
    sa.Column('lemah', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('diperbarui_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['materi_id'], ['materi.id'], name=op.f('fk_level_soal_siswa_materi_id_materi'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_level_soal_siswa')),
    sa.UniqueConstraint('siswa_id', 'materi_id', name=op.f('uq_level_soal_siswa_siswa_id'))
    )
    op.create_table('hasil_tes_materi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasil_tes_id', sa.Integer(), nullable=False),
    sa.Column('materi_id', sa.String(), nullable=False),
    sa.Column('jumlah_soal', sa.Integer(), nullable=False),
    sa.Column('jumlah_benar', sa.Integer(), nullable=False),
    sa.Column('akurasi', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=True),
    sa.Column('status_pemetaan', sa.Enum('cukup', 'belum_cukup', 'belum_teruji', name='statuspemetaan', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['hasil_tes_id'], ['hasil_tes.id'], name=op.f('fk_hasil_tes_materi_hasil_tes_id_hasil_tes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materi_id'], ['materi.id'], name=op.f('fk_hasil_tes_materi_materi_id_materi'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hasil_tes_materi')),
    sa.UniqueConstraint('hasil_tes_id', 'materi_id', name=op.f('uq_hasil_tes_materi_hasil_tes_id'))
    )
    op.create_table('paket_tes_soal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paket_tes_id', sa.Integer(), nullable=False),
    sa.Column('soal_id', sa.String(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('materi_id', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('mudah', 'menengah', 'sulit', name='levelsoal', native_enum=False), nullable=False),
    sa.Column('jawaban_dipilih', sa.String(), nullable=True),
    sa.Column('is_benar', sa.Boolean(), nullable=True),
    sa.Column('dibuka_pada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dijawab_pada', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['materi_id'], ['materi.id'], name=op.f('fk_paket_tes_soal_materi_id_materi')),
    sa.ForeignKeyConstraint(['paket_tes_id'], ['paket_tes.id'], name=op.f('fk_paket_tes_soal_paket_tes_id_paket_tes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['soal_id'], ['soal.id'], name=op.f('fk_paket_tes_soal_soal_id_soal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paket_tes_soal')),
    sa.UniqueConstraint('paket_tes_id', 'soal_id', name='uq_paket_tes_soal_paket_soal'),
    sa.UniqueConstraint('paket_tes_id', 'urutan', name='uq_paket_tes_soal_paket_urutan')
    )
    with op.batch_alter_table('aturan_kenaikan_tingkat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skor_pretest_jalur_cepat', sa.Numeric(precision=5, scale=2, asdecimal=False), server_default='90', nullable=False))
        batch_op.add_column(sa.Column('rata_level_min', sa.Numeric(precision=3, scale=2, asdecimal=False), server_default='2.0', nullable=False))
        batch_op.drop_column('persentase_kompetensi_cukup_min')
        batch_op.create_check_constraint(op.f('ck_aturan_kenaikan_tingkat_ck_aturan_kenaikan_skor_pretest_rentang'), 'skor_pretest_jalur_cepat >= 0 AND skor_pretest_jalur_cepat <= 100')
        batch_op.create_check_constraint(op.f('ck_aturan_kenaikan_tingkat_ck_aturan_kenaikan_rata_level_rentang'), 'rata_level_min >= 1 AND rata_level_min <= 3')

    with op.batch_alter_table('hasil_tes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paket_tes_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_hasil_tes_paket_tes_id'), ['paket_tes_id'])
        batch_op.create_foreign_key(batch_op.f('fk_hasil_tes_paket_tes_id_paket_tes'), 'paket_tes', ['paket_tes_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('riwayat_evaluasi_kenaikan', schema=None) as batch_op:
        # Riwayat fase 1 semuanya evaluasi setelah simulasi.
        batch_op.add_column(sa.Column('jalur', sa.String(), server_default='jalur_simulasi', nullable=False))
        batch_op.add_column(sa.Column('rata_level_aktual', sa.Numeric(precision=3, scale=2, asdecimal=False), nullable=True))
        batch_op.add_column(sa.Column('rata_level_target', sa.Numeric(precision=3, scale=2, asdecimal=False), nullable=True))
        batch_op.add_column(sa.Column('syarat_level_lulus', sa.Boolean(), nullable=True))
        batch_op.drop_column('syarat_kompetensi_lulus')
        batch_op.drop_column('persentase_cukup_target')
        batch_op.drop_column('persentase_cukup_aktual')
    with op.batch_alter_table('riwayat_evaluasi_kenaikan', schema=None) as batch_op:
        batch_op.alter_column('jalur', server_default=None)

    # ### end Alembic commands ###

    # --- Data ---------------------------------------------------------------
    # Nasional tidak ada lagi di fase 2; akses & aturan yang merujuknya ikut
    # terhapus lewat ON DELETE CASCADE.
    op.execute("DELETE FROM tingkat_seleksi WHERE urutan = 3")
    # Tingkat pertama yang dulu 'terbuka' secara default kini harus lewat
    # pre-test dulu.
    op.execute(
        "UPDATE akses_tingkat_siswa SET status = 'pretest_terbuka' "
        "WHERE status = 'terbuka' AND dibuka_karena = 'default_awal'"
    )
    # Akses tingkat lanjut yang dibuka fase 1 (evaluasi/admin) belum pernah
    # lewat pre-test tingkat itu — 'terbuka' fase 2 berarti pre-test selesai,
    # jadi siswa ini diarahkan ke pre-test dulu (bukan terkunci).
    op.execute(
        "UPDATE akses_tingkat_siswa SET status = 'pretest_terbuka' "
        "WHERE status = 'terbuka' AND tingkat_seleksi_id IN "
        "(SELECT id FROM tingkat_seleksi WHERE urutan > 1)"
    )
    op.execute(
        "UPDATE akses_tingkat_siswa SET dibuka_karena = 'override_admin' "
        "WHERE dibuka_karena = 'manual_admin'"
    )
    op.execute(
        "UPDATE akses_tingkat_siswa SET dibuka_karena = 'jalur_simulasi' "
        "WHERE dibuka_karena = 'lulus_evaluasi'"
    )
    # Aturan default Kabupaten -> Provinsi (fase 1 tidak pernah mengisinya).
    op.execute(
        "INSERT INTO aturan_kenaikan_tingkat "
        "(tingkat_asal_id, tingkat_tujuan_id, skor_simulasi_min, skor_pretest_jalur_cepat, rata_level_min) "
        "SELECT asal.id, tujuan.id, 75, 90, 2.0 FROM tingkat_seleksi asal, tingkat_seleksi tujuan "
        "WHERE asal.urutan = 1 AND tujuan.urutan = 2 "
        "ON CONFLICT (tingkat_asal_id, tingkat_tujuan_id) DO NOTHING"
    )
    op.execute(
        "INSERT INTO aturan_adaptif (tingkat_seleksi_id, jumlah_soal_pretest, ambang_lemah) "
        "SELECT id, 30, 50 FROM tingkat_seleksi "
        "ON CONFLICT (tingkat_seleksi_id) DO NOTHING"
    )


def downgrade() -> None:
    """Downgrade schema. Data akses/aturan tidak dipulihkan persis (Nasional
    dibuat ulang tanpa akses siswa)."""
    op.execute(
        "INSERT INTO tingkat_seleksi (nama, urutan) VALUES ('Nasional', 3) "
        "ON CONFLICT (urutan) DO NOTHING"
    )
    op.execute(
        "UPDATE akses_tingkat_siswa SET status = 'terbuka' WHERE status = 'pretest_terbuka' "
        "AND dibuka_karena = 'default_awal'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_evaluasi_kenaikan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persentase_cukup_aktual', sa.NUMERIC(precision=5, scale=2), server_default='0', autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('persentase_cukup_target', sa.NUMERIC(precision=5, scale=2), server_default='0', autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('syarat_kompetensi_lulus', sa.BOOLEAN(), server_default=sa.false(), autoincrement=False, nullable=False))
        batch_op.drop_column('syarat_level_lulus')
        batch_op.drop_column('rata_level_target')
        batch_op.drop_column('rata_level_aktual')
        batch_op.drop_column('jalur')

    with op.batch_alter_table('hasil_tes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hasil_tes_paket_tes_id_paket_tes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_hasil_tes_paket_tes_id'), type_='unique')
        batch_op.drop_column('paket_tes_id')

    with op.batch_alter_table('aturan_kenaikan_tingkat', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_aturan_kenaikan_tingkat_ck_aturan_kenaikan_rata_level_rentang'), type_='check')
        batch_op.drop_constraint(op.f('ck_aturan_kenaikan_tingkat_ck_aturan_kenaikan_skor_pretest_rentang'), type_='check')
        batch_op.add_column(sa.Column('persentase_kompetensi_cukup_min', sa.NUMERIC(precision=5, scale=2), server_default='80', autoincrement=False, nullable=False))
        batch_op.drop_column('rata_level_min')
        batch_op.drop_column('skor_pretest_jalur_cepat')

    op.drop_table('paket_tes_soal')
    op.drop_table('hasil_tes_materi')
    op.drop_table('level_soal_siswa')
    with op.batch_alter_table('paket_tes', schema=None) as batch_op:
        batch_op.drop_index('uq_paket_tes_pretest_per_siswa_tingkat', postgresql_where=sa.text("jenis_tes = 'pre_test'"))

    op.drop_table('paket_tes')
    op.drop_table('aturan_adaptif')
    # ### end Alembic commands ###
