"""tambah tabel latihan dan latihan_jawaban

Revision ID: 22bf7cd6a8a8
Revises: 0014
Create Date: 2026-10-01 00:21:37.898128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22bf7cd6a8a8'
down_revision: Union[str, Sequence[str], None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latihan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('materi_id', sa.String(), nullable=False),
    sa.Column('tingkat_seleksi_id', sa.Integer(), nullable=False),
    sa.Column('nilai', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('jumlah_benar', sa.Integer(), nullable=False),
    sa.Column('jumlah_salah', sa.Integer(), nullable=False),
    sa.Column('total_soal', sa.Integer(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('diselesaikan_pada', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('jumlah_benar >= 0', name=op.f('ck_latihan_ck_latihan_jumlah_benar_nonneg')),
    sa.CheckConstraint('jumlah_salah >= 0', name=op.f('ck_latihan_ck_latihan_jumlah_salah_nonneg')),
    sa.CheckConstraint('nilai >= 0 AND nilai <= 100', name=op.f('ck_latihan_ck_latihan_nilai_rentang')),
    sa.CheckConstraint('total_soal > 0', name=op.f('ck_latihan_ck_latihan_total_soal_positif')),
    sa.ForeignKeyConstraint(['materi_id'], ['materi.id'], name=op.f('fk_latihan_materi_id_materi'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tingkat_seleksi_id'], ['tingkat_seleksi.id'], name=op.f('fk_latihan_tingkat_seleksi_id_tingkat_seleksi'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_latihan'))
    )
    with op.batch_alter_table('latihan', schema=None) as batch_op:
        batch_op.create_index('ix_latihan_siswa_tingkat_materi', ['siswa_id', 'tingkat_seleksi_id', 'materi_id'], unique=False)

    op.create_table('latihan_jawaban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latihan_id', sa.Integer(), nullable=False),
    sa.Column('soal_id', sa.String(), nullable=False),
    sa.Column('jawaban', sa.String(), nullable=True),
    sa.Column('is_benar', sa.Boolean(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['latihan_id'], ['latihan.id'], name=op.f('fk_latihan_jawaban_latihan_id_latihan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['soal_id'], ['soal.id'], name=op.f('fk_latihan_jawaban_soal_id_soal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_latihan_jawaban')),
    sa.UniqueConstraint('latihan_id', 'soal_id', name=op.f('uq_latihan_jawaban_latihan_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latihan_jawaban')
    with op.batch_alter_table('latihan', schema=None) as batch_op:
        batch_op.drop_index('ix_latihan_siswa_tingkat_materi')

    op.drop_table('latihan')
    # ### end Alembic commands ###
